from graph.neo4j_client import Neo4jClient

class GraphBuilder:
    def __init__(self):
        from graph.neo4j_client import Neo4jClient
        self.client = Neo4jClient()

    def build_graph_from_cypher(self, cypher_script: str):
        """
        Executes a raw Cypher script generated by the LLM.
        Splits by semicolon to handle multiple statements.
        """
        if not cypher_script:
            return

        # Simple cleanup
        cypher_script = cypher_script.replace("```cypher", "").replace("```", "")
        
        # Split by semicolon (naive splitting, might break on semicolons in strings but acceptable for this demo)
        statements = [s.strip() for s in cypher_script.split(';') if s.strip()]

        for statement in statements:
            try:
                self.client.execute_query(statement)
            except Exception as e:
                print(f"Failed to execute Cypher: {statement[:50]}... Error: {e}")

    def close(self):
        self.client.close()
